version: '3.8'

networks:
  phalconnet:
    driver: ${NETWORKS_DRIVER}

volumes:
  phalcon:
    driver: ${VOLUMES_DRIVER}


services:

### PHP-NGINX ##############################################
    php-nginx:
      build:
        context: ./php-nginx
      volumes:
      - ${APP_CODE_PATH_HOST}:/app
      - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      - ${APP_CODE_PATH_HOST}/storage/logs:/app/storage/logs
      ports:
        - "${NGINX_HOST_HTTP_PORT}:80"
        - "${NGINX_HOST_HTTPS_PORT}:443"
      networks:
        - phalconnet

### MySQL ################################################
    mysql:
      build:
        context: ./mysql
        args:
          - MYSQL_VERSION=${MYSQL_VERSION}
      environment:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - TZ=${WORKSPACE_TIMEZONE}
      volumes:
        - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
        - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
      ports:
        - "${MYSQL_PORT}:3306"
      networks:
        - phalconnet
